# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb2',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('groupname', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'friendsList',
                'verbose_name': '\u6d4b\u8bd5\u8868',
                'verbose_name_plural': '\u6d4b\u8bd5\u8868',
            },
        ),
    ]
