# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_user', '0002_tb2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb2',
            table='hello_user.friendsList',
        ),
    ]
