# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_user', '0003_auto_20170814_1217'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb2',
            table='friendsList',
        ),
    ]
