# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_user', '0004_auto_20170814_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb2',
            name='groupname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tb2',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
